### ISSUE TITLE
Bug: makeblastdb "FASTA-Reader: Title ends with at least 50 valid amino acid characters.  Was the sequence accidentally put in the title line?"

### ISSUE THREAD

**Issue by wegnerce** [DittmarLab/HGTector#15]
This is not a bug related to HGTector.

While setting up HGTector I realized that the BLAST version on our server is causing trouble. I did not use databaser.py to set up the protein database, but I downloaded the standard database. After unpacking everything I wanted to create the BLAST database using the settings specified in databaser.py, but I was getting this error.

```
FASTA-Reader: Title ends with at least 50 valid amino acid characters.  Was the sequence accidentally put in the title line?
```

A quick look at stdb.faa revealed no obvious issue. I decided to upgrade my blast version (from 2.2.31 --> 2.6.0) and the issue was gone.

Best

Carl-Eric

**Comment by qiyunzhu** [comment]
Hello @wegnerce that's interesting finding! Thanks for letting us know! - Qiyun
