### ISSUE TITLE
blastdbcmd error

### ISSUE THREAD

**Issue by TarsLi** [DittmarLab/HGTector#16]
Hi, 
I try to use local blast+ 2.4.0 program to annotate my data by HGTector. But an error occourred. The NR database i used was downloaded before, not by databaser.py.

**Error: [blastdbcmd] copri_1_1: OID not found
Error: [blastdbcmd] copri_1_1: OID not found
BLAST query/options error: Entry or entries not found in BLAST database**
 
**And here is my config.txt:**
interactive=0
selfTax=pcopri:165179
protdb=/home/wang/software/ncbi-blast-2.4.0+/nr/nr
taxdump=/home/wang/software/ncbi-blast-2.4.0+/taxdmp
prot2taxid=/home/wang/software/ncbi-blast-2.4.0+
threads=20
blastp=/home/wang/software/ncbi-blast-2.4.0+/bin/blastp
blastdbcmd=/home/wang/software/ncbi-blast-2.4.0+/bin/blastdbcmd
identity=30
coverage=50
ignoreTaxa=vector,synthetic,phage
graphFp=1
exOutlier=1
title=prevotella copri
outExcel=1

Thanks!

**Comment by qiyunzhu** [comment]
Hi @whynotlih , I guess you probably supplied the program with input files containing sequence titles only, instead of the actual multi-Fasta sequences. Is that the case?

**Comment by whynotlih** [comment]
I'm sorry that i actually supplied the program with multi-Fasta sequences. So what is wrong with my program?

**Comment by whynotlih** [comment]
I'm sorry that i actually supplied the program with multi-Fasta sequences. So what is wrong with my program?

**Comment by whynotlih** [comment]
**This is the massage in my terminal:**

Reading input data...
  copri_2: 3056 proteins.
Done. 3056 proteins from 1 set(s) to query.
Reading taxonomy database... done. 1656196 records read.
Reading protein-to-TaxID dictionary... done. 0 records read.
Reading taxonomy records from previous run(s)... done. 0 taxa and 0 ranks read.
Taxonomy of input protein sets:
Attempting to identify taxonomy of 1 protein set(s) :
  copri_2
Error: [blastdbcmd] copri_1_1: OID not found
Error: [blastdbcmd] copri_1_1: OID not found
BLAST query/options error: Entry or entries not found in BLAST database
Please refer to the BLAST+ user manual.
Use of uninitialized value in split at /home/wang/mydata/Lihao/annotation/HGT/scripts/searcher.pl line 589.
Error: Cannot identify the taxonomy of copri_2.
Error: Execution of searcher.pl failed. HGTector exists.

**Comment by qiyunzhu** [comment]
Closing the issue since it was related to a previous version of the program...
