### ISSUE TITLE
Analyzer.pl R problem 

### ISSUE THREAD

**Issue by mdieser** [DittmarLab/HGTector#18]
Hi - Thank you very much for making this script available! 
I am running into the following problem while executing analyzer.pl. The problem seems to be related to reading in the table. Please see below. What I can find is that the last two entries in the string of numbers are separated by a space rather than a comma. I ran the command multiple times but this is a reoccurring issue. Any suggestion to fix this problem would be truly appreciated. 

I wish you a great weekend,
best regards,

Markus

 

Computing statistics...
  All protein sets:
    Self group:
      Skipped.
    Close group:
      Global cutoff (0.25) = 10.900.
      Performing Hartigan's dip test... done.
      D = 0.038228, p-value = 2.2e-16
      The weight distribution is significantly non-unimodal.
      Performing kernel density estimation... done.
Problem running the R command:
d<-data.frame(x=c(-1.95084446,-1.76566503,...............................................,1.603058e-05,1.077472e-05,6.715086e-06,3.881277e-06,2.079954e-06,1.032685e-06 4.744944e-07))
Got the error:
 <text>:1:12757: unexpected numeric constant
1: 1135e-06,4.180106e-06,7.093232e-06,1.124340e-05,1.651814e-05,2.246770e-05,2.829661e-05,3.300089e-05,3.563260e-05,3.560213e-05,3.288999e-05,2.806529e-05,2.209492e-05,1.603058e-05,1.077472e-05,6

**Comment by mdieser** [comment]
I case somebody experiences the same issue.
Found a way around the problem by modifying the code. 
First I tried telling R to separate entries by 'comma' but the same error occurred. Again, the last two numbers were separated by a 'space'. I fixed the error by adding a line to the code that replaces 'spaces' by 'comma'. 

In Analyzer.pl

# identify local extrema using R package "pastecs"

            if ($toolExtrema) {
                if ($toolKDE < 2) {
		    my @dx1 = join (",", @dx);
		    my $dy1 = join (",", @dy);
		    $dy1 =~ tr/ /,/;
		    my @dy2 = $dy1;
		    $R->send("d<-data.frame(x=c(@dx1),y=c(@dy2))");
                    #$R->send("d<-data.frame(x=c(".join (",", @dx)."),y=c(".join (",", @dy)."))");
					
                }

**Comment by qiyunzhu** [comment]
Hello @mdieser , sorry for the late reply. I have been quite busy in the past month. Thank you for pointing out this issue and providing a fix! Looks interesting. Not sure why the variables `@dx` and `@dy` have unseparated spaces in them. I will look into the upstream codes. Thanks again!

**Comment by mdieser** [comment]
No problem at all. Maybe you could help me with another issue please. I am working on a dataset with 36 bacterial genomes. They all are strains within the same genus. I ran the dataset twice using the genus as the self group and either the class level or the domain (Bacteria) as the distal group. Are these appropriate group identifications or would recommend different ones?  Thanks in advance - Markus

**Comment by mdieser** [comment]
CORRECTION: class level or the domain (Bacteria) were selected as the close group, NOT distal group. My apologies.
