### ISSUE TITLE
Cutoff

### ISSUE THREAD

**Issue by mdieser** [DittmarLab/HGTector#19]
Hi - I have been playing around with my input parameter for a while now but regardless what I include in the self-, close-, or distant-group, my cutoffs are always <0.03. It also does not matter if several bacterial genomes of the same genus are analyzed simultaneously or a single genome. 
Inputs that I tried:
self group: tax ID of the genome of interest; the genus of the single genome of interest
close group: the genus of the single genome of interest; closely related other genera; family-, order,- class-, and phylum-level; and domain
Papers that report on using HGTector all show much higher cutoffs for the close and distant group. Can you please help me identify what this low cutoff means or can we please discuss any analytical errors I may have caused?

Thanks again,

Markus

**Comment by mdieser** [comment]
Solved! A great  answer to fix this problem is provided in the comments "Reporter: Generate reports of HGT prediction results - loop #3". The attached zip file in this comment includes helpful info to adjust settings in the config.file.

**Comment by qiyunzhu** [comment]
Hello @mdieser Sorry for not responding so far. I was bit too involved in my current works. Glad that you solved it!
