### ISSUE TITLE
ftplib.error_temp: 425 Unable to build data connection: Connection refused

### ISSUE THREAD

**Issue by yoyohashao** [DittmarLab/HGTector#2]
Hey, here's the script I used and the outcome. Besides the 425 error, I also found the output database was named stdb instead of Arc-test. 

SEBASTIANs-MacBook-Pro:scripts FLFLFLLF$ python databaser.py -format=none -range=archaea -subsample=1 -out Arc-test

Databaser: generate taxonomically balanced, non-redundant proteome database.
Author: Qiyun Zhu (qzhu@jcvi.org)
Affiliation: J. Craig Venter Institute
Last updated: Oct 24, 2015

Connecting to the NCBI FTP server... done.
Downloading the NCBI taxonomy database... done.
Reading the NCBI taxonomy database... done.
  1404643 taxa read.
Downloading the NCBI representative genome list... done.
Reading the NCBI representative genome list... done.
  4183  genomes read.
Reading RefSeq genome list... done.
  473 genomes read.
Subsampling genomes... done.
  313 genomes retained.
Reading RefSeq genomic data... done.
  313 genomes to download.
Extracting non-redundant proteomic data from NCBI RefSeq...
  25 50 75 100 125 150 175 200
Traceback (most recent call last):
  File "databaser.py", line 315, in <module>
    ftp.retrbinary('RETR ' + downfile, fout.write, 1024)
  File "//anaconda/lib/python2.7/ftplib.py", line 414, in retrbinary
    conn = self.transfercmd(cmd, rest)
  File "//anaconda/lib/python2.7/ftplib.py", line 376, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "//anaconda/lib/python2.7/ftplib.py", line 358, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "//anaconda/lib/python2.7/ftplib.py", line 249, in sendcmd
    return self.getresp()
  File "//anaconda/lib/python2.7/ftplib.py", line 222, in getresp
    raise error_temp, resp
ftplib.error_temp: 425 Unable to build data connection: Connection refused

**Comment by qiyunzhu** [comment]
It looks to me a network error. There is one fix you can try: open
databaser.py, find line #68: ftp.set_pasv(False), remove it and save, then
run again and see if it works. By the way, you should do -out=Arc-test
instead of -out Arc-test. - Qiyun

**Comment by yoyohashao** [comment]
I modified the script and problem was solved. Thanks!
