### ISSUE TITLE
Use of uninitialized value in concatenation

### ISSUE THREAD

**Issue by FlamySYSU** [DittmarLab/HGTector#21]
Hello Qiyunzhu,

Thks for your excellent software, but when I was runing the sample in this directory,I got into trouble with analyzer.pl:

my code :perl scripts/analyzer.pl sample
and be reported as follow:
-> Analyzer: Identify putative HGT-derived genes based on search results. <-
Warning: Prediction result from a previous analysis is detected.
Press Enter to overwrite, or Ctrl+C to exit:

Reading taxonomic information... done.
Analyzing taxonomic information... done.
  All input genomes belong to species Galdieria sulphuraria (TaxID: 130081).
Analysis will work on the following taxonomic ranks:
  Self: (user-defined self) Galdieria (TaxID: 83373) (1 members),
  Close: (user-defined close) Eukaryota (TaxID: 2759) (1 members),
  Distal: all other organisms.
Press Enter to continue, or Ctrl+C to exit:
Reading protein sets...done. 1 sets detected.
Analyzing search results...
0-------------25-------------50------------75------------100%
gsul has 100 proteins. Analyzing...

 done.
Raw data are saved in result/statistics/rawdata.txt.
You may conduct further analyses on these data.
Press Enter to continue, or Ctrl+C to exit:

Computing statistics...
  All protein sets:
 done.
Use of uninitialized value in concatenation (.) or string at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mean"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mean"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"stdev"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"stdev"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"min"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"min"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"max"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"max"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"median"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"median"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mad"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mad"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q1"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q1"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q3"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q3"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"cutoff"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"cutoff"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value in concatenation (.) or string at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mean"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mean"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"stdev"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"stdev"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"min"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"min"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"max"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"max"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"median"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"median"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mad"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mad"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q1"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q1"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q3"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q3"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"cutoff"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"cutoff"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value in concatenation (.) or string at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mean"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mean"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"stdev"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"stdev"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"min"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"min"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"max"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"max"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"median"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"median"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mad"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"mad"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q1"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q1"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q3"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"q3"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"cutoff"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Use of uninitialized value $h{"cutoff"} in sprintf at analyzer.pl line 1256, <STDIN> line 3.
Result is saved in result/statistics/fingerprint.txt.
Press Enter to proceed with prediction, or Ctrl+C to exit:
Predicting... done.
Prediction results are saved in result/detail/.

I tried to change version of perl in different service but doesnt work,could you give me some advice?t

Thanks again!

**Comment by qiyunzhu** [comment]
Sorry for not addressing this issue. Let me close since it was related to a previous version of the program before I re-engineered the whole program.
