### ISSUE TITLE
ftplib.error_temp: 421 Idle timeout (60 seconds): closing control connection

### ISSUE THREAD

**Issue by 473021677** [DittmarLab/HGTector#24]
Hi, here's the script I used and the error reports. 
[yuanyang@localhost HGTector_nr_manually_2]$ python databaser.py
-> Databaser: generate taxonomically balanced, non-redundant genome and proteome database. <-

Usage:
  python scripts/databaser.py [-format=none|blast] [-range=all|microbe|etc] [-represent=no|auto|filename] [-subsample=0|1|2...] [-out=dbname]
Note:
  By default, the script will download NCBI RefSeq genomic data of microbial organisms, keep one genome per species, plus all NCBI-defined representative genomes.
  Use "-help" to display details of program parameters.
Press Enter to continue or Ctrl+C to exit...
Connecting to the NCBI FTP server... done.
Downloading the NCBI taxonomy database... Traceback (most recent call last):
  File "databaser.py", line 103, in <module>
    ftp.retrbinary('RETR ' + 'taxdump.tar.gz', fout.write, 1024)
  File "/data/data/yuanyang/softwares/lib/python2.7/ftplib.py", line 425, in retrbinary
    return self.voidresp()
  File "/data/data/yuanyang/softwares/lib/python2.7/ftplib.py", line 231, in voidresp
    resp = self.getresp()
  File "/data/data/yuanyang/softwares/lib/python2.7/ftplib.py", line 217, in getresp
    resp = self.getmultiline()
  File "/data/data/yuanyang/softwares/lib/python2.7/ftplib.py", line 203, in getmultiline
    line = self.getline()
  File "/data/data/yuanyang/softwares/lib/python2.7/ftplib.py", line 193, in getline
    if not line: raise EOFError
EOFError

**Comment by qiyunzhu** [comment]
Hello @473021677 It seems to be an FTP connection issue. For example, maybe your home wifi or your institute intranet does not allow the protocol. Could you try a different Internet service?

**Comment by 473021677** [comment]
Hi Qiyun:
    Thanks for your detailed response. I have tried a different Internet service, but the same problem applies. yoyohashao has asked you similar questions. The error report is "ftplib.error_temp: 425 Unable to build data connection: Connection refused". You have given him one suggestion. It is "open
databaser.py, find line #68: ftp.set_pasv(False), remove it and save, then run again and see if it works". I have tried it but the same problem applies. I wonder if I can solve this problem by modified the file databaser.py. Thanks!

Best regards,
Yuan
