### ISSUE TITLE
 BrokenPipeError: [Errno 32] Broken pipe  : databaser.py

### ISSUE THREAD

**Issue by peterthorpe5** [DittmarLab/HGTector#25]
**Version**: HGTector0.2.2

Dear HGTector,

I am trying to prepare a database, based on the given examples, I used the following command (see below). I have tried various ways of altering this command and I receive different errors. However, this is the closest to the example documented by you. Most error seems to return the error poiting to line 333 File "scripts/databaser.py", line 333, in <module>
    ftp.cwd('/genomes/all/GCF/' + dir)

Questions: I know you have tested this on bacteria (your paper), but can the tool work for Eukaryota organisms? (your lab works on fleas, so surely you have used it for insects?). If this database preparation keeps failing can I pass it a BLAST done manually (to skip this step)?

Regards, 

Peter Thorpe

**Command**:
> python scripts/databaser.py -format=blast -range=protozoa,fungi,archaea,bacteria,invertebrate,plant,vertebrate_mammalian,vertebrate_other,viral -subsample=1 -represent=auto -out="MyEukarie"

-> Databaser: generate taxonomically balanced, non-redundant genome and proteome database. <-

Connecting to the NCBI FTP server... done.
Downloading the NCBI taxonomy database... done.
Reading the NCBI taxonomy database... done.
  2112593 taxa read.
Downloading the NCBI representative genome list... done.
Reading the NCBI representative genome list... done.
  5800  genomes read.
Reading RefSeq genome list... done.
  166196 genomes read.
Subsampling genomes... done.
  33273 genomes retained.
Downloading non-redundant genomic data from NCBI RefSeq...
  25 50 75 100 125 150 175 200 225 250 275 300 325 350 375 400 425 450 475 500 525 550 575 600 625 650 675 700 725 750 775 800 825 850 875 900 925 950 975 1000 1025 1050 1075 Traceback (most recent call last):
  File "scripts/databaser.py", line 333, in <module>
    ftp.cwd('/genomes/all/GCF/' + dir)
  File "/shelf/apps/pjt6/conda/envs/HGtector/lib/python3.6/ftplib.py", line 631, in cwd
    return self.voidcmd(cmd)
  File "/shelf/apps/pjt6/conda/envs/HGtector/lib/python3.6/ftplib.py", line 277, in voidcmd
    self.putcmd(cmd)
  File "/shelf/apps/pjt6/conda/envs/HGtector/lib/python3.6/ftplib.py", line 199, in putcmd
    self.putline(line)
  File "/shelf/apps/pjt6/conda/envs/HGtector/lib/python3.6/ftplib.py", line 194, in putline
    self.sock.sendall(line.encode(self.encoding))
**BrokenPipeError: [Errno 32] Broken pipe**

**Comment by qiyunzhu** [comment]
Let me close this issue. Sorry didn't have a chance to respond. It is likely due to network connection issue.
