### ISSUE TITLE
is the pre-built database still available?

### ISSUE THREAD

**Issue by korinalb** [DittmarLab/HGTector#26]
I'm getting a '404 page not found' error at the web address provided in the README.md to download the standard database:

https://u21438014.dl.dropboxusercontent.com/u/21438014/HGTector/stdb_20170630.tar

**Comment by qiyunzhu** [comment]
It may be due to some recent Dropbox policy change. Can you try this one and let me know if it works? Thanks!

https://www.dropbox.com/s/mqwkm0tl7r0p7qe/stdb_20170630.tar?dl=0

**Comment by korinalb** [comment]
Yes that works now, thanks!

**Comment by qiyunzhu** [comment]
You are welcome!
