### ISSUE TITLE
Reporter: Generate reports of HGT prediction results - loop

### ISSUE THREAD

**Issue by kafker** [DittmarLab/HGTector#3]
Hello,
I am working on a set of 86 proteins and during the final step (Report), the following message: "Reporter: Generate reports of HGT prediction results." appear infinite times on the terminal screen. Is this normal for a set of 86 proteins?
Here my configuration file:

interactive=0
selfTax=BCP1:191292
httpBlast=1
taxBlast=1
alnBlast=1
evalue=1e-10
identity=30
nHits=100
ignoreSubspecies=1
selfRank=genus
graphFp=1
exOutlier=1
dipTest=1
bwF=0.3
plotKDE=1
title=report
byOrthology=1

Thank you!

p.s really interesting software!

**Comment by qiyunzhu** [comment]
Hello Kafker,

Thanks for your interest in our program! Based on your configuration file I
cannot figure out what may cause the problem. If possible can you zip and
send me your entire working directory, so that I can try to debug?

Best,
Qiyun

**Comment by kafker** [comment]
Hello Qiyun,
Thank you for your quick reply. Attached the working directory. 
Best,
Kafker
[HGTector-master.zip](https://github.com/DittmarLab/HGTector/files/155387/HGTector-master.zip)

**Comment by qiyunzhu** [comment]
Hello Kafker,

Sorry but I have been busy in the past few days. Now I have completed
testing your input data. It worked fine. I switched off several parameters
in the config.txt file to make the process smooth. Attached please find the
entire output directory. Also I recommend doing local blast instead of
remote, because the remote version is extremely slow at my place.

Best,
Qiyun

**Comment by kafker** [comment]
Dear Qiyun,

Thanks for the advice and thanks for doing this but I can not find the
attached file.

Best,

Andrea
Il 11/mar/2016 20:23 "Qiyun Zhu" <notifications@github.com> ha scritto:

> Hello Kafker,
>
> Sorry but I have been busy in the past few days. Now I have completed
> testing your input data. It worked fine. I switched off several parameters
> in the config.txt file to make the process smooth. Attached please find the
> entire output directory. Also I recommend doing local blast instead of
> remote, because the remote version is extremely slow at my place.
>
> Best,
> Qiyun
>
>

**Comment by qiyunzhu** [comment]
Hi Andrea, I cannot figure out how to attach a file in Github comment
system. May I send you the file via regular email? Mine is
qiyunzhu@gmail.com. - Qiyun

**Comment by kafker** [comment]
Sure!
Thank you
Il 13/mar/2016 20:07 "Qiyun Zhu" <notifications@github.com> ha scritto:

> Hi Andrea, I cannot figure out how to attach a file in Github comment
> system. May I send you the file via regular email? Mine is
> qiyunzhu@gmail.com. - Qiyun
>
>

**Comment by qiyunzhu** [comment]
Hi Andrea, I mean, could you let me know your email address by sending a
regular email to my address (qiyunzhu@gmail.com) so that I can send you the
file? Thanks! - Qiyun

**Comment by kafker** [comment]
Here my email

andres.firrincieli@gmail.com

Best
Andrea
Il 15/mar/2016 20:24 "Qiyun Zhu" <notifications@github.com> ha scritto:

> Hi Andrea, I mean, could you let me know your email address by sending a
> regular email to my address (qiyunzhu@gmail.com) so that I can send you
> the
> file? Thanks! - Qiyun
>
