### ISSUE TITLE
BLAST Database error: No database names were found in alias file

### ISSUE THREAD

**Issue by sarbashis** [DittmarLab/HGTector#4]
Hi,
      I have created blast database using databaser.py code. Its takes all most 12 hours and showed database successfully created. But while running HGTector.pl, I got  "Database error: No database names were found in alias file". I have set the path for the protdb in the config file. I am wondering what I am missing.

**Comment by qiyunzhu** [comment]
Hello sarbashis, Thanks for letting me know the issue. It seems that the blastp program cannot find the database in the given location. Can you post the content of config.txt?

**Comment by sarbashis** [comment]
Hi qiyunzhu,
                    Here is the database path I used.
interactive=0
# Search tool #
searchTool=BLAST                     # Use NCBI-BLAST+ for search
blastp=blastp
blastdbcmd=blastdbcmd

# Databases #
protdb=/home/sarba/program/HGTector/db/blast/stdb                # local BLAST database
taxdump=/home/sarba/program/HGTector/db/taxdump             # local taxonomy database
#prot2taxid=/path/to/gi2taxid.dmp     # GI-to-TaxID dictionary

My blast folder contains

stdb.00.phr  stdb.01.pin  stdb.02.pnd  stdb.03.pni  stdb.04.pog  stdb.05.psd  stdb.06.psi  stdb.07.psq  stdb.09.phr  stdb.10.pin  stdb.11.pnd  stdb.12.pni  stdb.13.pog  stdb.14.psd  stdb.15.psi  stdb.16.psq  
stdb.00.pin  stdb.01.pnd  stdb.02.pni  stdb.03.pog  stdb.04.psd  stdb.05.psi  stdb.06.psq  stdb.08.phr  stdb.09.pin  stdb.10.pnd  stdb.11.pni  stdb.12.pog  stdb.13.psd  stdb.14.psi  stdb.15.psq  stdb.17.phr  stdb.pal
stdb.00.pnd  stdb.01.pni  stdb.02.pog  stdb.03.psd  stdb.04.psi  stdb.05.psq  stdb.07.phr  stdb.08.pin  stdb.09.pnd  stdb.10.pni  stdb.11.pog  stdb.12.psd  stdb.13.psi  stdb.14.psq  stdb.16.phr  stdb.17.pin
stdb.00.pni  stdb.01.pog  stdb.02.psd  stdb.03.psi  stdb.04.psq  stdb.06.phr  stdb.07.pin  stdb.08.pnd  stdb.09.pni  stdb.10.pog  stdb.11.psd  stdb.12.psi  stdb.13.psq  stdb.15.phr  stdb.16.pin  stdb.17.pnd
stdb.00.pog  stdb.01.psd  stdb.02.psi  stdb.03.psq  stdb.05.phr  stdb.06.pin  stdb.07.pnd  stdb.08.pni  stdb.09.pog  stdb.10.psd  stdb.11.psi  stdb.12.psq  stdb.14.phr  stdb.15.pin  stdb.16.pnd  stdb.17.pni
stdb.00.psd  stdb.01.psi  stdb.02.psq  stdb.04.phr  stdb.05.pin  stdb.06.pnd  stdb.07.pni  stdb.08.pog  stdb.09.psd  stdb.10.psi  stdb.11.psq  stdb.13.phr  stdb.14.pin  stdb.15.pnd  stdb.16.pni  stdb.17.pog
stdb.00.psi  stdb.01.psq  stdb.03.phr  stdb.04.pin  stdb.05.pnd  stdb.06.pni  stdb.07.pog  stdb.08.psd  stdb.09.psi  stdb.10.psq  stdb.12.phr  stdb.13.pin  stdb.14.pnd  stdb.15.pni  stdb.16.pog  stdb.17.psd
stdb.00.psq  stdb.02.phr  stdb.03.pin  stdb.04.pnd  stdb.05.pni  stdb.06.pog  stdb.07.psd  stdb.08.psi  stdb.09.psq  stdb.11.phr  stdb.12.pin  stdb.13.pnd  stdb.14.pni  stdb.15.pog  stdb.16.psd  stdb.17.psi
stdb.01.phr  stdb.02.pin  stdb.03.pnd  stdb.04.pni  stdb.05.pog  stdb.06.psd  stdb.07.psi  stdb.08.psq  stdb.10.phr  stdb.11.pin  stdb.12.pnd  stdb.13.pni  stdb.14.pog  stdb.15.psd  stdb.16.psi  stdb.17.psq

**Comment by sarbashis** [comment]
Solved. Few files in the database was not generated.

**Comment by qiyunzhu** [comment]
Glad to hear that! Good luck!
