### ISSUE TITLE
HGTector for plants

### ISSUE THREAD

**Issue by AliceZhengy2019** [DittmarLab/HGTector#40]
Hi Qiyun,

I'm so glad to see the update of HGTector.

I have worked on this software for a couple of days and found that the TaxID of Phyllostachys (38705) was not found in taxonomy database. And then I realized that the database was based on microbes.

Is it possible to use HGTector2 to predict the putative horizontal transferred genes in plants? Such as Phyllostachys (38705)?

Thanks!

**Comment by qiyunzhu** [comment]
Hello @AliceZhengy2019 Thanks for your interest. Yes HGTector2 can work on plants. You just need to build a [database](../blob/master/doc/database.md) that contains plants. For example:

```bash
hgtector database --cats plant -o .
```

If  you expect that the genes are from, say, Bacteria, you can do:

```bash
hgtector database --cats bacteria,plant -o .
```

**Comment by AliceZhengy2019** [comment]
Hi Qiyun,

Thanks for your immediate reply.

I wondered whether there's some genes in plants that horizontally transferred from microbe. So maybe it is reasonable to search against the microbe database. But, during the analyze process, only the taxdump file need to be updated with all the taxonomy ID included because the analyze don't depend on database (or maybe it depends but I don't realize). 

With the above assumption, I chose the protein sequences of _Phyllostachys edulis_ (38705) as input file. The search process was successful with some sequences unaligned. However, error was detected during the analyze process (see below).

![图片 1](https://user-images.githubusercontent.com/54054891/68911691-c92bd700-0790-11ea-9709-46c6499b1257.png)

I don't know whether the assumption is wrong or certain modifications of HGTector2 are needed to get it  better work for detecting plant HGT?

I also downloaded the plant database as you recommended. A error raised as: "EOFError: Compressed file ended before the end-of-stream marker was reached". Do you have any ideas about that?

Thank you so much!

**Comment by qiyunzhu** [comment]
Hi @AliceZhengy2019 , thanks for reporting these potential bugs!

First question, the error message seems to be relevant to the invalid format of "nodes.dmp" file under "taxdump1". Can you post the first few lines of this file?

Second question, can you post the screen output, like the one you did for the first question?

Thank you!

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu, thanks for reply!

1. After rechecking the format of 'nodes.dmp',  new error raised (see below). I have specified the self group (38705) and close group (38820) in the script, but it didn't work. The Taxdump file was attached as [taxdump_Allsciname.zip].

<img width="985" alt="New error" src="https://user-images.githubusercontent.com/54054891/68941381-ade8b800-07e0-11ea-9cb5-21d462ebcd00.png">

[taxdump_Allsciname.zip](https://github.com/DittmarLab/HGTector/files/3851376/taxdump_Allsciname.zip)

2. For the plant database, please find the screen output of error below (Only parts of 'Using local file XXX' lines were list since they were a little too large).

<img width="525" alt="PlantDatabase1" src="https://user-images.githubusercontent.com/54054891/68941638-69115100-07e1-11ea-8009-53400868517c.png">
<img width="876" alt="PlantDatabase2" src="https://user-images.githubusercontent.com/54054891/68941639-69a9e780-07e1-11ea-9503-9807389c2d79.png">

Thanks again for your immediate and kind reply!

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu,

When I executed the example gsul.txt as recommended, an error raised as follow. Do you have any idea about it?

<img width="874" alt="Example" src="https://user-images.githubusercontent.com/54054891/69027379-b6700700-0a09-11ea-8f77-3ef02debf6d1.png">

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu,

When I executed the example "gsul.txt" as recommended, an error was reported. Any ideas about it?

<img width="874" alt="Example" src="https://user-images.githubusercontent.com/54054891/69027651-a4429880-0a0a-11ea-8691-a53004fbcdd3.png">

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu,

I downloaded a new taxdump.tar.gz from NCBI, merged it with the one you provided and it seems worked. But a new error raised as follow. Do you know how to deal with it?

![Error](https://user-images.githubusercontent.com/54054891/69476281-38e63580-0e13-11ea-8519-1db4e9c04fae.png)

**Comment by qiyunzhu** [comment]
Hello @AliceZhengy2019 sorry for the late response as I was busy recently. Thanks for providing detailed screen outputs which are helpful for me to debug the program. Let me try to address individual questions:

1. The example run (`gsul.txt`). This error message means that a variable `self.timeout` is not set. This is strange to me as I thought this variable should always have a value. The default value `900` is defined in `config.yml`.

Therefore, the problem may be that HGTector2 couldn't find `config.yml`. I don't know why. The file should be located at:

```
/home/zmbin/miniconda2/envs/hgtector/lib/python3.7/site-packages/hgtector/config.yml 
```

Did you see it? If yes, you may try to copy this file to the current directory, and run the example again. Is the problem resolved? (If yes, I will think again why HGTector2 couldn't find the file in its original location.)

2. The screen output suggests that all genes were removed because they were considered as either ORFans or outliers, thus none was left for the statistics to operate on. Not sure why. But if you can resolve 1 (the `config.yml` problem), you may get the program running correctly. If not, let's discuss again. You may share with me `scores.tsv` so that I can do a sanity check.

Hope this helps!

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu, thanks for taking time to reply! 

I have copied the **config.yml** file to the current example directory, but it still didn't work.

<img width="942" alt="Example error" src="https://user-images.githubusercontent.com/54054891/69584913-4d941a80-1019-11ea-81c7-44ce96aa563d.png">

Here is the **scores.txt** as **.tsv** doesn't support for upload. 

[scores.txt](https://github.com/DittmarLab/HGTector/files/3889131/scores.txt)

**Comment by qiyunzhu** [comment]
Hi @AliceZhengy2019 I realized that the `timeout` issue is a bug of my program. I just fixed it ( #42 ). Can you please test again?

I also checked the `scores.txt` file you provided. It has problems. The `self` and `close` columns are empty, which suggests that the grouping scenario is problematic. Once you have confirmed that the `timeout` issues is resolved, let's look at this issue again.

Thanks!

**Comment by AliceZhengy2019** [comment]
Hi  @qiyunzhu, I have inserted the sentence "**get_config(self, key, 'remote.{}'.format(key))**" into search.py and the following script into analyze.py as you suggested in #42 . Put the fixed search.py and analyze.py in : /home/zmbin/miniconda2/envs/hgtector/lib/python3.7/site-packages/hgtector. (Just want to check whether I did the right thing)

<img width="662" alt="analyze" src="https://user-images.githubusercontent.com/54054891/69837379-69055c80-1289-11ea-8516-52b98100675e.png">

Then the next error raised

<img width="778" alt="Example error2" src="https://user-images.githubusercontent.com/54054891/69837336-23e12a80-1289-11ea-9e7c-c9a2ffbcecb4.png">

**Comment by qiyunzhu** [comment]
Hello @AliceZhengy2019 I think the easier way is to update the program by executing the installation command again: `pip install git+https://github.com/DittmarLab/HGTector.git`. Your manual patch should work too, but according to the error message you provided, it seems that some indentations weren't handled correctly. Python is an indent-sensitive language. Using inprecise number of spaces or mixing tabs and spaces will cause errors.

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu, thanks for the response. I have reinstalled the latest HGTector and tried both local database and remote search. It still didn't work.

<img width="1068" alt="Example error-cannot obtain sequences" src="https://user-images.githubusercontent.com/54054891/70433365-8245ae80-1abc-11ea-9cb8-57b7ee54ca8d.png">

<img width="1062" alt="Example error-time out" src="https://user-images.githubusercontent.com/54054891/70433109-d308d780-1abb-11ea-8c2f-db600a7839e4.png">

**Comment by qiyunzhu** [comment]
Hello @AliceZhengy2019 This looks to me a network issue. The local search you did was actually not local because it attempted to pull sequences form NCBI (note: the example file has accessions but no sequence). I think you can just skip the example and do your formal local search. That should work.

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu, thanks for the immediate response. I have tried the local analyze with my own data, but it still didn't work. All genes were removed as either ORFans or outliers.

<img width="1157" alt="Error1210-2" src="https://user-images.githubusercontent.com/54054891/70487483-7f84a100-1b30-11ea-9b9a-343ddf89842a.png">
<img width="776" alt="Error1210-1" src="https://user-images.githubusercontent.com/54054891/70487244-a8f0fd00-1b2f-11ea-9cd4-4505ad2ffec4.png">

Would you please help check whether there's something wrong with the search result (Bamboo24examples.txt) and analyze result (scores24.txt)? Thank you so much!

[Bamboo24examples.txt](https://github.com/DittmarLab/HGTector/files/3942583/Bamboo24examples.txt)
[scores24.txt](https://github.com/DittmarLab/HGTector/files/3942584/scores24.txt)

**Comment by qiyunzhu** [comment]
Hi @AliceZhengy2019 Sorry for the very late response, but I have been very busy in the past month. Have you figured it out already? If not and you still need the answer, I will try to work it out.

**Comment by AliceZhengy2019** [comment]
Hi @qiyunzhu  thanks for the reply. The problem has not been solved. Maybe there is no HGT in bamboo, or my bamboo data is not compatible with HGTector. I'm afraid I need to give up searching HGT in bamboo. Anyway, I really appreciate your help!
