### ISSUE TITLE
No hit is assigned to distal group. Cannot predict HGTs.

### ISSUE THREAD

**Issue by hdxieruize** [DittmarLab/HGTector#45]
Hi everyone
I'm now using HGTector2 to analyse the HGT event of one archaea genome. I set up the local database according to commands provided by author. But there was a problem when I used the Analyze function.  I don't know why?

**Comment by qiyunzhu** [comment]
Hi @hdxieruize Sorry for the late response. In your case, the grouping scenario automatically inferred by the program is not optimal, and you will need to manually specify groups. You may take a look at the tutorial [second run](https://github.com/DittmarLab/HGTector/blob/master/doc/2ndrun.md). Especially this example command:
```
hgtector analyze ... --self-tax 562,620 --close-tax 1236,28216
```
