### ISSUE TITLE
About donor results!

### ISSUE THREAD

**Issue by sunnycqcn** [DittmarLab/HGTector#47]
Hello Qiyun,
It is glad to see your HGTector has been updated. This version is so easy to use. Three years ago I used your 2.0 version. And I got good results. However, I did not published my results since I updated my genome version. Currently, I almost am done my genome. I used small sample data get a list. However,
I used the command join -t$'\t' -j1 <(sort hgts/o55h7.txt) <(tail -n+2 scores.tsv | grep ^o55h7$'\t' | cut -f2,8 | sort) > o55h7.donor.txt to get the donor results. The donor results is empty.
The attachment is my hgt list.
[o55h7.txt](https://github.com/DittmarLab/HGTector/files/4434196/o55h7.txt)

**Comment by qiyunzhu** [comment]
Hi @sunnycqcn , thank you for your interest! The version you used three years ago might be "0.2" instead of "2.0" :) Your question may be because the input genome name is not "o55h7" but a custom string, in which case you need to modify the Bash command. Could you please share scores.tsv as well?

**Comment by sunnycqcn** [comment]
Hello Qiyun,
The attachment is my scores file.
Thanks,
Fuyou
[scores.txt](https://github.com/DittmarLab/HGTector/files/4440320/scores.txt)

**Comment by qiyunzhu** [comment]
Thanks for sharing. So the sample name is "L022_L022.proteins" instead of "o55h7". You will need to modify the command accordingly, such as:
```
join -t$'\t' -j1 <(sort hgts/o55h7.txt) <(tail -n+2 scores.tsv | grep ^L022_L022.proteins$'\t' | cut -f2,8 | sort) > o55h7.donor.txt
```

**Comment by sunnycqcn** [comment]
I got it.
Thanks,
Fuyou
