### ISSUE TITLE
HGTector stuck at "Step 1: Searcher - batch protein sequence homology search."

### ISSUE THREAD

**Issue by kafker** [DittmarLab/HGTector#5]
Hi Qiyunzhu,
As you suggested, I have created, without any issue, a local database using the databaser.py. However,  HGTector fail to progress through the first step. After 24 hours, it is still working on the first set of 10 proteins:

"Validating task...
Done.

Step 1: Searcher - batch protein sequence homology search.

-> Searcher: Batch sequence homology searching and filtering. <-
Reading input data...
  WP: 7278 proteins.
Done. 7278 proteins from 1 set(s) to query.
Reading search results from previous run(s)...
Done. 0 results found, remaining 7278 proteins to search.
Reading taxonomy database... done. 1491434 records read.
Reading protein-to-TaxID dictionary... done. 34512566 records read.
Reading taxonomy records from previous run(s)... done. 1 taxa and 13 ranks read.
Enter the TaxID of WP, or press Enter if you don't know:578459
Taxonomy of input protein sets:
  WP: Rhodotorula graminis WP1 (578459)
Batch homology search of WP (7278 queries) started.
  BLASTing KPV71431.1,KPV71432.1,KPV71433.1,KPV71434.1,KPV71435.1,KPV71436.1,KPV71437.1,KPV71438.1,KPV71439.1,KPV71440.1..."

This sound suspicious.

Here is my config file: 

"selfTax=Rhoba:578459
searchTool=BLAST
blastp=blastp
blastdbcmd=blastdbcmd
queries=10
protdb=/media/universita/SAMSUNG/HGTector-master/scripts/blast/stdb
taxdump=/media/universita/SAMSUNG/HGTector-master/scripts/taxdump
prot2taxid=/media/universita/SAMSUNG/HGTector-master/gi2taxid.txt
getAln=1
identity=45
maxHits=100
selfGroup=4751
closeGroup=2759
graphFp=1
boxPlot=1
histogram=1 
densityPlot=1
scatterPlot=1
howCO=4
globalCO=0.25
exOutlier=1
dipTest=1
dipSig=0.05
bwF=0.3
toolExtrema=1 
modKCO=1
plotKDE=1
minHits=1
minSize=34
title=wpout
outText=1 
outHTML=1"

... and the list of files inside the blast/ directory:

"stdb.00.phr, stdb.00.pin, stdb.00.pnd, stdb.00.pni, stdb.00.pog, stdb.00.psd, stdb.00.psi, stdb.00.psq, stdb.01.phr, stdb.01.pin, stdb.01.pnd, stdb.01.pni, stdb.01.pog, stdb.01.psd, stdb.01.psi, stdb.01.psq, stdb.02.phr, stdb.02.pin, stdb.02.pnd, stdb.02.pni, stdb.02.pog, stdb.02.psd, stdb.02.psi, stdb.02.psq, stdb.03.phr, stdb.03.pin, stdb.03.pnd, stdb.03.pni, stdb.03.pog, stdb.03.psd, stdb.03.psi, stdb.03.psq, stdb.04.phr, stdb.04.pin, stdb.04.pnd, stdb.04.pni, stdb.04.pog, stdb.04.psd, stdb.04.psi, stdb.04.psq, stdb.05.phr, stdb.05.pin, stdb.05.pnd, stdb.05.pni, stdb.05.pog, stdb.05.psd, stdb.05.psi, stdb.05.psq, stdb.06.phr, stdb.06.pin, stdb.06.pnd, stdb.06.pni, stdb.06.pog, stdb.06.psd, stdb.06.psi, stdb.06.psq, stdb.07.phr, stdb.07.pin, stdb.07.pnd, stdb.07.pni, stdb.07.pog, stdb.07.psd, stdb.07.psi, stdb.07.psq, stdb.08.phr, stdb.08.pin, stdb.08.pnd, stdb.08.pni, stdb.08.pog, stdb.08.psd, stdb.08.psi, stdb.08.psq, stdb.09.phr, stdb.09.pin, stdb.09.pnd, stdb.09.pni, stdb.09.pog, stdb.09.psd, stdb.09.psi, stdb.09.psq, stdb.10.phr, stdb.10.pin, stdb.10.pnd, stdb.10.pni, stdb.10.pog, stdb.10.psd, stdb.10.psi, stdb.10.psq, stdb.pal"

Thank you!

**Comment by qiyunzhu** [comment]
Hello Kafker,

Thank you for letting me know this. I looked at your configuration file. It
seems that everything is correct. Let us first suspect that the
computational load may be the problem. When you run this forever-running
Blast, how much CPU load and memory does it take? (e.g., by unix command
"top")

Best,
Qiyun

**Comment by kafker** [comment]
Hello,
Thank you for the quick reply. I will check that and let you know. However, I am working on a workstation with 64 Gb of RAM, so I do not think it should be a problem. 
Best,
Andrea

**Comment by kafker** [comment]
Dear Qiyun,
Problem solved, now it work. Seems that writing blastp outputs into an external archive was the problem. 

Follow the CPU and Memory usage while it is running now on my workstation:
top - 14:41:54 up 6 days,  3:32,  5 users,  load average: 26.98, 24.73, 21.45
Tasks: 544 total,   1 running, 543 sleeping,   0 stopped,   0 zombie
%Cpu(s): 95.4 us,  0.8 sy,  0.0 ni,  3.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem:  65924036 total, 63918632 used,  2005404 free, 12727252 buffers
KiB Swap: 67054588 total,    70676 used, 66983912 free. 40191152 cached Mem
It's is really high!
Thanks
Andrew

**Comment by qiyunzhu** [comment]
Hello Andrea, Great to know that! As I remember, Blast is slow but does not
take to much memory, since the databases are stored as multiple volumes
(1GB each by default?) on the disk. Modern alternatives such as Diamond,
however, cache the entire database in memory. Those program will cause a
substantial burden on desktop computers. Meanwhile, another source of
memory usage (probably your situation) is that HGTector caches the entire
GI-to-TaxID table in memory, which consumes dozens of GBs. This is
optional, and can be switched off if the Blast database already contains
TaxID information (for example, NCBI nr has it). In GUI.html there is a
guideline of how to append TaxID when constructing Blast database. Best,
Qiyun
