### ISSUE TITLE
TaxID nan is not found in taxonomy database.

### ISSUE THREAD

**Issue by xieyg5** [DittmarLab/HGTector#55]
Hello 
I used hgtector  to analyze my MAGsm,but system can not auto-infer taxonomy for  my MAGs, so I specify manually tax ID , it still has errors.
(hgtector) [xxx@node1 2.gene_pre]$ hgtector analyze -i search  -o analyze  -t /xxx/database/hgtector/taxdump/  --input-tax bin.19:189774
Analysis started at 2020-06-27 20:51:20.514960.
Reading local taxonomy database...
Done. Read 40245 taxa.
Reading homology search results...
  bin.19: 3049 proteins.
Done. Read search results of 1 samples.
User-specified TaxIDs of input genomes:
  bin.19: 189774 (unclassified Chloroflexi (miscellaneous)).
Refining taxonomy database...
Traceback (most recent call last):
  File "/xxx/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 422, in _get_taxon
    return taxdump[tid]
KeyError: nan

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/xxx/miniconda3/envs/hgtector/bin/hgtector", line 96, in <module>
    main()
  File "/xxx/miniconda3/envs/hgtector/bin/hgtector", line 35, in main
    module(args)
  File "/xxx/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 134, in __call__
    self.assign_taxonomy()
  File "/xxx/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/analyze.py", line 349, in assign_taxonomy
    self.taxdump = refine_taxdump(self.sum_taxids(), self.taxdump)
  File "/xxx/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 864, in refine_taxdump
    ancs = set().union(*[get_lineage(x, taxdump) for x in tids])
  File "/xxx/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 864, in <listcomp>
    ancs = set().union(*[get_lineage(x, taxdump) for x in tids])
  File "/xxx/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 654, in get_lineage
    taxon = _get_taxon(cid, taxdump)
  File "/xxx/miniconda3/envs/hgtector/lib/python3.8/site-packages/hgtector/util.py", line 424, in _get_taxon
    raise ValueError(f'TaxID {tid} is not found in taxonomy database.')
ValueError: TaxID nan is not found in taxonomy database.

Could you help me? Thanks for your help very much.

Best regards

**Comment by qiyunzhu** [comment]
Hello @xieyg5 It is mostly likely that the manually entered TaxID 189774 is not found in the taxonomy database. Could you check it? If that's the case, you will have to replace it with the taxonomically / phylogenetically closest TaxID instead.

**Comment by xieyg5** [comment]
thanks, I checked that TaxID 189774  was in the names.dmp and nodes.dmp. it can define the taxID 189774  (User-specified TaxIDs of input genomes:bin.19: 189774 (unclassified Chloroflexi (miscellaneous))), the problem seems to be in refining taxonomy database... and I used some other TaxID  the same error occurred.

**Comment by xieyg5** [comment]
> Hello @xieyg5 It is mostly likely that the manually entered TaxID 189774 is not found in the taxonomy database. Could you check it? If that's the case, you will have to replace it with the taxonomically / phylogenetically closest TaxID instead.

thanks, I checked that TaxID 189774 was in the names.dmp and nodes.dmp. it can define the taxID 189774 (User-specified TaxIDs of input genomes:bin.19: 189774 (unclassified Chloroflexi (miscellaneous))), the problem seems to be in refining taxonomy database... and I used some other TaxID the same error occurred.

**Comment by qiyunzhu** [comment]
@xieyg5 Thanks for the further information. On a second thought, I guess that some TaxIDs in your search result are not in the taxonomy database. In your `search` directory, does each file look like this?

```
# ID: WP_000064228.1
# Length: 714
# Product: methylmalonyl-CoA mutase
# Score: 1396.3
# Hits: 33
NP_311814.1	99.7	0.0e+00	1392.1	100.0	386585
YP_002409252.1	99.4	0.0e+00	1391.7	100.0	585057
YP_002413943.1	99.4	0.0e+00	1391.3	100.0	585056
NP_708678.2	99.4	0.0e+00	1390.2	100.0	198214
YP_001006157.1	86.3	0.0e+00	1221.8	100.0	393305
```

The last column is TaxID. Can you check if some of them are missing or not present in your taxonomy database?

For example, this command can find whether there is any missing TaxID.

```bash
cat search/*.tsv | grep -v ^# | cut -f6 | grep -c ^$
```

This can check whether some TaxIDs are not found in your database:

```bash
join -v1 <(cat search/*.tsv | grep -v ^# | cut -f6 | sort | uniq) <(cat /xxx/taxdump/nodes.dmp | cut -f1 | sort)
```

(Disclaimer: I am not sure if these commands will work... Do it with your own scrutiny.)

**Comment by xieyg5** [comment]
> @xieyg5 Thanks for the further information. On a second thought, I guess that some TaxIDs in your search result are not in the taxonomy database. In your `search` directory, does each file look like this?
> 
> ```
> # ID: WP_000064228.1
> # Length: 714
> # Product: methylmalonyl-CoA mutase
> # Score: 1396.3
> # Hits: 33
> NP_311814.1	99.7	0.0e+00	1392.1	100.0	386585
> YP_002409252.1	99.4	0.0e+00	1391.7	100.0	585057
> YP_002413943.1	99.4	0.0e+00	1391.3	100.0	585056
> NP_708678.2	99.4	0.0e+00	1390.2	100.0	198214
> YP_001006157.1	86.3	0.0e+00	1221.8	100.0	393305
> ```
> 
> The last column is TaxID. Can you check if some of them are missing or not present in your taxonomy database?
> 
> For example, this command can find whether there is any missing TaxID.
> 
> ```shell
> cat search/*.tsv | grep -v ^# | cut -f6 | grep -c ^$
> ```
> 
> This can check whether some TaxIDs are not found in your database:
> 
> ```shell
> join -v1 <(cat search/*.tsv | grep -v ^# | cut -f6 | sort | uniq) <(cat /xxx/taxdump/nodes.dmp | cut -f1 | sort)
> ```
> 
> (Disclaimer: I am not sure if these commands will work... Do it with your own scrutiny.)

thanks，I checked that the .tsv file by your commands , it  has the taxID and  the taxIDs  in .tsv file are also in database .  I download 2019.10.21 database but the same error still occurred.  finally I change the version to 2.0b1, it  didn't have any problems.   maybe there is something wrong with version 2.0b2 .

**Comment by surh** [comment]
I had the same issue. By manually running the diamond command, I discovered that this happens because some taxonomic levels in nodes.dmp have taxonomic ranks not allowed by diamond.

In my case the ranks `clade` and 'strain` were causing problems. You need to modify those to something valid. This is an incompatibility between NCBi taxonomy and diamond.

The full list of diamond valid taxonomic ranks is [here](https://github.com/bbuchfink/diamond/blob/7463f47283ef4dee3189807399b3ebed0084c06e/src/data/taxonomy.cpp#L38-L40).

**Comment by qiyunzhu** [comment]
@surh Thanks for sharing the information! This is great to know. I like DIAMOND but its behavior changes from version to version. Recently I noticed that NCBI taxdump is more robust than previous. Ranks `isolate`, `strain` and `subspecies` are more meaningful and prevalent.

One way to bypass this without messing with NCBI or DIAMOND version is: Run DIAMOND manually, with `--outfmt 6` so that it will generate standard m8 output without taxonomy, then use HGTector's `--precomp` to load this m8 file, together with `--taxmap` plus NCBI's accession2taxid mapping. HGTector will assign taxonomy to the hits.

@xieyg5 Please let us know if this helps. Thanks!

**Comment by xieyg5** [comment]
> @surh Thanks for sharing the information! This is great to know. I like DIAMOND but its behavior changes from version to version. Recently I noticed that NCBI taxdump is more robust than previous. Ranks `isolate`, `strain` and `subspecies` are more meaningful and prevalent.
> 
> One way to bypass this without messing with NCBI or DIAMOND version is: Run DIAMOND manually, with `--outfmt 6` so that it will generate standard m8 output without taxonomy, then use HGTector's `--precomp` to load this m8 file, together with `--taxmap` plus NCBI's accession2taxid mapping. HGTector will assign taxonomy to the hits.
> 
> @xieyg5 Please let us know if this helps. Thanks!

@qiyunzhu @surh  thanks for your help.  I was updated diamond software, the error did not appear with hgtector.
