### ISSUE TITLE
about the GTDB database

### ISSUE THREAD

**Issue by caris1988** [DittmarLab/HGTector#64]
Hello, I have another question.
I'm trying to use the GTDB database for HGTector analyses. Is the file "gtdb_r89_rep_genomes.protein.faa.tar.gz" the one that I should dowload? Thanks!

**Comment by qiyunzhu** [comment]
Hello @caris1988 I am not familiar with the filename you mentioned. If this file contains the protein sequences (faa), then yes, you need it to build your reference protein sequence database. The taxonomy information needed for HGTector is in here: https://data.ace.uq.edu.au/public/gtdb/data/releases/release89/89.0/gtdbtk_r89_data.tar.gz. But perhaps the file you mentioned also has the taxonomy information and in which case you can use it.

**Comment by caris1988** [comment]
Thanks very much for your reply. The file I mentioned contains amino acid FASTA sequences for all protein-coding genes of the GTDB representative genomes (predicted with Prodigal). 


It seems that I should still use the protein sequences&nbsp;from Genbank to build reference database, and just use the GTDB taxonomy file instead of the NCBI taxonomy file. Is that right?


Thank you!




Ruolin Cheng&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by qiyunzhu** [comment]
@caris1988 No. You should use the protein sequences provided by GTDB to build the reference database, then use the mapping of proteins to genomes provided by GTDB, then use the mapping of genome to taxonomy provided by GTDB. Note that the data in NCBI is way ahead of GTDB, so mixing them will cause incongruence between protein, genome and taxonomy.

**Comment by caris1988** [comment]
Thanks. I tried to use the&nbsp;gtdb_to_taxdump.py script to produce the nodes.dmp and names.dmp files, but something went wrong while building the reference database (for diamond). Howerver, another scripts seemed to work,&nbsp;https://github.com/nick-youngblut/gtdb_to_taxdump/blob/master/gtdb_to_taxdump.py 
Thanks agains for your kind reply!









 
@caris1988 No. You should use the protein sequences provided by GTDB to build the reference database, then use the mapping of proteins to genomes provided by GTDB, then use the mapping of genome to taxonomy provided by GTDB. Note that the data in NCBI is way ahead of GTDB, so mixing them will cause incongruence between protein, genome and taxonomy.

**Comment by qiyunzhu** [comment]
@caris1988 Thanks for reporting your experience! Very helpful!
