### ISSUE TITLE
Analyzer.pl failed 

### ISSUE THREAD

**Issue by jaalcort** [DittmarLab/HGTector#7]
Hello Qiyunzhu,
Thank you for this new tool to analyze HGT that is useful for beginners in computing. 
I am working with a genome released this year and looking for HGT on its genus. The first problem i had was the taxID that wasn't recognized  by the searcher.pl. Instead this, it performed the BLAST for all proteins on this data set and it was included in the Taxonomy files.

But in Step 2, the script analyzer.pl failed and i don't know why it was happening. 

This was the message:
-> Analyzer: Identify putative HGT-derived genes based on search results. <-
Reading taxonomic information... done.
Analyzing taxonomic information... done.
Unknown TaxID 0.
Execution of analyzer.pl failed.

The config.txt was like for 4939 genes

title=FischerellaNIES  
selfTax=FisN:1752063  
searchTool=BLAST  
httpBlast=1  
httpDb=nr  
nHits=500  
evalue=1e-10  
identity=50  
ignoreSubspecies=1  
selfGroup=1189                      # Stigonematales
closeGroup=1117                      # Cyanobacteria
howCO=4  
bwF=0.3  
plotKDE=1  
modKCO=1  
POE=1   

I tried to change the directory files if it could the problem, and i changed the config.txt a few times to run with the same NEXUS blast files and it doesn't work. 
Thanks for yor help. !

**Comment by qiyunzhu** [comment]
Dear jaalcort,

Sorry for the late reply, as I just had a busy week. I looked at the information you provided. It seems to me that the configuration is reasonable. The error occurred when analyzer.pl couldn't recognize the TaxID of your input genome (Unknown TaxID 0), but I found that you actually already set selfTax=FisN:1752063. Therefore, I cannot directly tell what could be wrong. I noticed that you set httpBlast=1. This instructed the program to connect to the NCBI server to conduct all Blast searches. This may cause some uncertainties. I suggest that you download and built the reference genome database in local (using the built-in databaser.py), and run local Blast (or Diamond), to see if the problem just go away.

You may reach me at _qiyunzhu@gmail.com_ if you want to send me intermediate files for diagnosis.

Best,
Qiyun

**Comment by jaalcort** [comment]
Dear Qiyun Zhu, 

I created a local database with only bacteria and archaea, with 5 representative genomes for each species taxa. I tried to run HGTector and it worked for 85 proteins, but then i had the same error than 4th issue.   

BLASTing BAU04203.1,BAU04204.1,BAU04205.1... (4854 proteins)BLAST Database error: No alias or index file found for protein database [/media/storage02_300gb/jalcorta/HGTector/HGTDB.faa] in search path [/media/storage02_300gb/jalcorta/HGTector:/var/lib/blastdb:]

the config.txt that i used was: 

selfTax=FisN:1752063
protdb=/media/storage02_300gb/jalcorta/HGTector/HGTDB.faa
taxdump=/media/storage02_300gb/jalcorta/HGTector/taxdump
prot2taxid=/media/storage02_300gb/jalcorta/HGTector/gi2taxid.txt
identity=50
coverage=80
selfGroup=1189
closeGroup=1117 
title=FISNIES
byOrthology=1
outExcel=1
realign=ClustalW
trimSeq=Gblocks
buildTree=phyml
aaModel=JTT
bsTree=1000

the command that i used for databaser.py was:

python ./scripts/databaser.py -format=blast -range=archaea,bacteria -subsample=5 -represent=auto -out="HGTDB"

Thank you for your time. 
Best regards.

**Comment by qiyunzhu** [comment]
Hello jaalcort,

I think the problem is that the BLAST database path wasn't properly set. It
shouldn't be HGTDB.faa, which is a multi-fasta file containing all protein
sequences. Instead, there should be an independent folder containing the
compiled blast database. For example (I guess),
protdb=/media/storage02_300gb/jalcorta/HGTector/*blast*/HGTDB. Can you try
that and let me know if the problem is solved? Thanks!

Best,
Qiyun

**Comment by jaalcort** [comment]
Hello Qiyun, 

Sorry by come back since a long time. I solved that problem and it was a due by network problem with the NCBI site. When it crashed it left me with those incomplete files. 
Then i was working with a few genomes alone and the kernel values that calculated the program were good. 
Now, i want to work with a set of genomes, but i had the next problem. 

I didn't put the selfTax ID for the group in config.txt, because it was'n recognized and because the script asked me the taxID after, when i run the searcher.pl. Now i am stucked in the analyzer.pl script and the message was: 

-> Analyzer: Identify putative HGT-derived genes based on search results. <-
Reading taxonomic information... done.
Analyzing taxonomic information...Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
 done.
Unknown TaxID .

The config.txt was:

protdb=/media/storage02_300gb/jalcorta/microbeDB/HGTector/blast/stdb2
taxdump=/media/storage02_300gb/jalcorta/microbeDB/HGTector/taxdump
prot2taxid=/media/storage02_300gb/jalcorta/microbeDB/HGTector/gi2taxid.txt
identity=50
coverage=80
title=ORTOM
byOrthology=1
outExcel=1
realign=ClustalW
trimSeq=Gblocks
buildTree=phyml
aaModel=JTT
bsTree=1000

And the taxIDs of the set were:
NIES:1752063; TSYN:197221; 7702:292563; OSCI:864702

Another question is if can i work with a genome without a taxID (e.g. a genome sequenced by my  group)?. 

Best Regards!
(Thank you for your patience, i saw that you answered all questions in all issues and that is great :) )

**Comment by qiyunzhu** [comment]
Hello jaalcort,

I am so sorry for not responding for such a loooong time. I was extremely busy with other stuff. Now I that I realized that the outdated **databaser.py** has blocked everyone from using HGTector happily, I spent some time to update it to match the new NCBI FTP file system. If you download the master [branch](https://github.com/DittmarLab/HGTector/archive/master.zip) you will get it.

**Comment by jaalcort** [comment]
Qiyun, 

Here again. I installed again HGTector and i tried with four genomes from the same species to watch HGT in orthologous genes. All was OK until analyzer.pl finished and the individual outputs were fine. After that,  this message appeared continually. 
-> Reporter.pl: Generate reports of HGT prediction results. <-
Then, this message appeared continually. 
Error: Identification of orthology failed.
And finally:
Execution of analyzer.pl failed.

I tried to run orthologer.pl and it showed this message.
Argument "E-value" isn't numeric in numeric gt (>) at ./scripts/orthologer.pl line 128, <IN> line 10.

I had good results with each genome separatedly, but when i tried to watch HGT in orthologous genes i have failed. 
I you can guide me with this issue i will be so much grateful. 

The config.txt was:
selfTax=FisN:1752063,F7414:306281,F7521:98439,FJSC11:741277
protdb=/home/visita/jaime/HGTector-master/blast/HGTDB
taxdump=/home/visita/jaime/HGTector-master/taxdump
prot2taxid=/home/visita/jaime/HGTector-master/gi2taxid.txt
identity=50
coverage=80
selfGroup=1190
closeGroup=1117 
title=TERMOSSV
byOrthology=1
outExcel=1
realign=ClustalW
trimSeq=Gblocks
buildTree=phyml
aaModel=JTT
bsTree=1000
 
Best regards!.

**Comment by qiyunzhu** [comment]
Hi jaalcort, your configuration file looks fine. I guess that there may be
a bug in my code. You can try to edit orthologer.pl, add a new line "next
if /^\[/;" between lines 122 and 123, and test if the problem is solved.
Please let me know your result. Thanks! - Qiyun

**Comment by qiyunzhu** [comment]
Hi jaalcort, your configuration file looks fine. I guess that there may be a bug in my code. You can try to edit orthologer.pl, add a new line `next if /^\[/;` between lines 122 and 123, and test if the problem is solved. Please let me know your result. Thanks! - Qiyun

**Comment by jaalcort** [comment]
Qiyun, hi again. 
I edited the script and it works when i run  orthologer.pl.  
The process was: 

-> Orthologer: Identify orthologous groups based on homology search results. <-
Identifying orthologous groups (OGs)...
  Reading input proteins...  done. 14481 proteins read.
  Parsing BLAST results...
    JSC11 7414 NIES 7521
  done. 14481 OGs identified.
  Naming OGs... done.
  Sorting OGs... done.
  OG names and members exported as taxonomy/orthology.db.

But if you see the numbers, you will realize that each protein read was considered as an OG. Then the orthologous groups weren't identified. 

I tried all over again, and the HGTector.pl stopped at Reporter step, and i don't know if it's a problen related with orthologuer. The message was:  

-> Reporter: Generate reports of HGT prediction results. <-
Report by donor organism generated.
Can't use an undefined value as an ARRAY reference at /home/visita/jaime/HGTector-master/scripts/reporter.pl line 654.
Execution of analyzer.pl failed.

Thanks for your patience.

**Comment by brown-bio-lab** [comment]
Qiyun,
I have been struggling for two weeks with similar error messages with analyzer.pl.

I get this:
Step 2: Analyzer - predict HGT based on hit distribution statistics.

-> Analyzer: Identify putative HGT-derived genes based on search results. <-
Reading taxonomic information... done.
Analyzing taxonomic information...Argument "" isn't numeric in numeric ne (!=) at /media/scratch/amanda/HGTector/HGTector-master/scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at /media/scratch/amanda/HGTector/HGTector-master/scripts/analyzer.pl line 287.
 done.
Unknown TaxID .
Execution of analyzer.pl failed.

My config.txt file is:

title=CPpe
selfTax=cPpe:273135
protdb=/media/scratch/amanda/HGTector/HGTector-master/db/stdb
taxdump=/media/scratch/amanda/HGTector/HGTector-master/db/taxdump
prot2taxid=/media/scratch/amanda/HGTector/HGTector-master/db/prot.accession2taxid
threads=0
queries=0
nHits=100
maxHits=100
evalue=1e-4
identity=30
coverage=50
getAln=1
selfGroup=273135
closeGroup=768507
graphFp=1
boxPlot=1
histogram=1
densityPlot=1
howCO=4
bwF=0.3
plotKDE=1
modKCO=1
POE=1

Please let me know what could be causing this. I cannot seem to figure it out.
Thanks,

**Comment by ChaoLab** [comment]
@brown-bio-lab

**Comment by ChaoLab** [comment]
@brown-bio-lab

**Comment by ChaoLab** [comment]
@brown-bio-lab       Dear Brown, I encountered the same issue as you described. The error pops up, stating that something is wrong with Line 287. I guess that it should be related to the setting of "selfTax=" in the config file. Can I know how do you finally solve this problem? All my best!    From Chao.

**Comment by ChaoLab** [comment]
@jaalcort 
Dear Jaalcort, 
I read your comment on 29 Nov 2016, you have solved the problem of the "Unknown TaxID", which would cause an error pop of "Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287."

Can I know how you deal with that?  Maybe, you could email me to zczhou2017@gmail.com

Many thanks!

**Comment by Yliub** [comment]
@qiyunzhu Hello Qiyun,

I am runing the HGTector software with the version of 0.2.2, Some problems encountered at the step 2, as seen in the following error report:
-> Analyzer: Identify putative HGT-derived genes based on search results. <-
Reading taxonomic information... done.
Analyzing taxonomic information...Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
done.
Unknown TaxID .

The config.txt was:

protdb=/media/storage02_300gb/jalcorta/microbeDB/HGTector/blast/stdb2
taxdump=/media/storage02_300gb/jalcorta/microbeDB/HGTector/taxdump
prot2taxid=/media/storage02_300gb/jalcorta/microbeDB/HGTector/gi2taxid.txt
identity=50
coverage=80
title=ORTOM
byOrthology=1
outExcel=1
realign=ClustalW
trimSeq=Gblocks
buildTree=phyml
aaModel=JTT
bsTree=1000

And the taxIDs of the set were:
A1:469; A2:469; A3:469; A4:469.......................................A30:469
I  notice that the same bug had been repoted in previously query


do you known what's wrong with it?

![Uploading image.png…]()

**Comment by Yliub** [comment]
@qiyunzhu Hello Qiyun,

I am runing the HGTector software with the version of 0.2.2, Some problems encountered at the step 2, as seen in the following error report:
-> Analyzer: Identify putative HGT-derived genes based on search results. <-
Reading taxonomic information... done.
Analyzing taxonomic information...Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
Argument "" isn't numeric in numeric ne (!=) at ./scripts/analyzer.pl line 287.
done.
Unknown TaxID .

The config.txt was:

protdb=/media/storage02_300gb/jalcorta/microbeDB/HGTector/blast/stdb2
taxdump=/media/storage02_300gb/jalcorta/microbeDB/HGTector/taxdump
prot2taxid=/media/storage02_300gb/jalcorta/microbeDB/HGTector/gi2taxid.txt
identity=50
coverage=80
title=ORTOM
byOrthology=1
outExcel=1
realign=ClustalW
trimSeq=Gblocks
buildTree=phyml
aaModel=JTT
bsTree=1000

And the taxIDs of the set were:
A1:469; A2:469; A3:469; A4:469.......................................A30:469
I  notice that the same bug had been repoted in previously query


do you known what's wrong with it?

![image](https://user-images.githubusercontent.com/47737846/98969738-1f6d5a80-254a-11eb-9b03-be35704cc431.png)

**Comment by qiyunzhu** [comment]
Hi @Yliub Thanks for noting this. That was an issue of a very old version of HGTector which was written in Perl. Based on the description, I guess the problem was that the "TaxID" cannot be extracted by the program. Perhaps it is due to taxonomy database format updates since I first wrote the program. Since 2019 I have recoded the entire program using Python, and stopped maintaining the old version. I guess you are trying to compare results by new and old versions. But I am afraid that debugging the old program will not be effective given my current bandwidth. Is it possible that you use the new version?

**Comment by Yliub** [comment]
@qiyunzhu thanks for your reply, I have noticed the latest version of HGTector 2.0b2 released. And I try to apply it to predicted HGT events, yes, it works. but I just want to foucus on the potential donor at a specific phylogenetic level, for example at order or family level. It could be realize by the old version of 0.2.1 or 0.2.2, rather than 2.0b2. but when using the old version, it always encountered problems, so, could you please tell how can I predicted the potential donor on a specific phylogenetic level by using  HGTector 2.0b2? thanks a lot in advanced.

Regards,
liub

**Comment by Yliub** [comment]
@qiyunzhu Addtionally，in the old version 0.2.2, the problem of TaxID have been solved, however,  when I am runing the softwere, I  get just one hit per protein that too the same one with 100 percent identity. I guess that because the diamond version is lastest, so, I am now try to constructed the database by using diamond 0.7.12, I just using the command "diamond makedb --in db.faa -d db", do the datababe constructed by the above command will works on the HGTector 0.2.2? by the way, the databse was the pre-built default database as of 2019-10-21 provided by you. thank you very much.

**Comment by Yliub** [comment]
@qiyunzhu Addtionally，in the old version 0.2.2, the problem of TaxID have been solved, however, when I am runing the softwere, I get just one hit per protein that too the same one with 100 percent identity. I guess that because the diamond version is lastest (version 2.0.5), so, I am now try to constructed the database by using diamond 0.7.12, I just using the command "diamond makedb --in db.faa -d db", do the datababe constructed by the above command will works on the HGTector 0.2.2? by the way, the databse was the pre-built default database as of 2019-10-21 provided by you. thank you very much.

**Comment by Yliub** [comment]
@qiyunzhu could you pease provied me a database sample constructed by old version of diamond?

**Comment by Yliub** [comment]
@qiyunzhu could you pease provied me a database sample constructed by old version of diamond? or provided me a script working on HGTector 2.0b2 which could translate the Potential donor into a specific level ?
